/**
 * ISO 3166-1 countries — reference dataset for the repository forms
 *
 * This module carries the officially assigned ISO 3166-1 entries with
 * their alpha-2 and alpha-3 codes and short names in English and Spanish
 * (widely accepted Spanish exonyms). The repository forms use it to drive
 * the country select, to fill `country_code` (alpha-3, the stored shape)
 * from the chosen country, and to prefix the suggested repository code
 * (alpha-2, the house convention — `repository-code.ts`). Reference data
 * from the ISO 3166-1 standard; a dataset test pins uniqueness and spot
 * entries.
 *
 * @version v0.6.0
 */

export interface Country {
  /** ISO 3166-1 alpha-2, uppercase. */
  alpha2: string;
  /** ISO 3166-1 alpha-3, uppercase — the stored `country_code` shape. */
  alpha3: string;
  nameEn: string;
  nameEs: string;
}

export const COUNTRIES: readonly Country[] = [
  { alpha2: "AF", alpha3: "AFG", nameEn: "Afghanistan", nameEs: "Afganistán" },
  { alpha2: "AX", alpha3: "ALA", nameEn: "Åland Islands", nameEs: "Islas Åland" },
  { alpha2: "AL", alpha3: "ALB", nameEn: "Albania", nameEs: "Albania" },
  { alpha2: "DZ", alpha3: "DZA", nameEn: "Algeria", nameEs: "Argelia" },
  { alpha2: "AS", alpha3: "ASM", nameEn: "American Samoa", nameEs: "Samoa Americana" },
  { alpha2: "AD", alpha3: "AND", nameEn: "Andorra", nameEs: "Andorra" },
  { alpha2: "AO", alpha3: "AGO", nameEn: "Angola", nameEs: "Angola" },
  { alpha2: "AI", alpha3: "AIA", nameEn: "Anguilla", nameEs: "Anguila" },
  { alpha2: "AQ", alpha3: "ATA", nameEn: "Antarctica", nameEs: "Antártida" },
  { alpha2: "AG", alpha3: "ATG", nameEn: "Antigua and Barbuda", nameEs: "Antigua y Barbuda" },
  { alpha2: "AR", alpha3: "ARG", nameEn: "Argentina", nameEs: "Argentina" },
  { alpha2: "AM", alpha3: "ARM", nameEn: "Armenia", nameEs: "Armenia" },
  { alpha2: "AW", alpha3: "ABW", nameEn: "Aruba", nameEs: "Aruba" },
  { alpha2: "AU", alpha3: "AUS", nameEn: "Australia", nameEs: "Australia" },
  { alpha2: "AT", alpha3: "AUT", nameEn: "Austria", nameEs: "Austria" },
  { alpha2: "AZ", alpha3: "AZE", nameEn: "Azerbaijan", nameEs: "Azerbaiyán" },
  { alpha2: "BS", alpha3: "BHS", nameEn: "Bahamas", nameEs: "Bahamas" },
  { alpha2: "BH", alpha3: "BHR", nameEn: "Bahrain", nameEs: "Baréin" },
  { alpha2: "BD", alpha3: "BGD", nameEn: "Bangladesh", nameEs: "Bangladés" },
  { alpha2: "BB", alpha3: "BRB", nameEn: "Barbados", nameEs: "Barbados" },
  { alpha2: "BY", alpha3: "BLR", nameEn: "Belarus", nameEs: "Bielorrusia" },
  { alpha2: "BE", alpha3: "BEL", nameEn: "Belgium", nameEs: "Bélgica" },
  { alpha2: "BZ", alpha3: "BLZ", nameEn: "Belize", nameEs: "Belice" },
  { alpha2: "BJ", alpha3: "BEN", nameEn: "Benin", nameEs: "Benín" },
  { alpha2: "BM", alpha3: "BMU", nameEn: "Bermuda", nameEs: "Bermudas" },
  { alpha2: "BT", alpha3: "BTN", nameEn: "Bhutan", nameEs: "Bután" },
  { alpha2: "BO", alpha3: "BOL", nameEn: "Bolivia", nameEs: "Bolivia" },
  { alpha2: "BQ", alpha3: "BES", nameEn: "Bonaire, Sint Eustatius and Saba", nameEs: "Bonaire, San Eustaquio y Saba" },
  { alpha2: "BA", alpha3: "BIH", nameEn: "Bosnia and Herzegovina", nameEs: "Bosnia y Herzegovina" },
  { alpha2: "BW", alpha3: "BWA", nameEn: "Botswana", nameEs: "Botsuana" },
  { alpha2: "BV", alpha3: "BVT", nameEn: "Bouvet Island", nameEs: "Isla Bouvet" },
  { alpha2: "BR", alpha3: "BRA", nameEn: "Brazil", nameEs: "Brasil" },
  { alpha2: "IO", alpha3: "IOT", nameEn: "British Indian Ocean Territory", nameEs: "Territorio Británico del Océano Índico" },
  { alpha2: "BN", alpha3: "BRN", nameEn: "Brunei Darussalam", nameEs: "Brunéi" },
  { alpha2: "BG", alpha3: "BGR", nameEn: "Bulgaria", nameEs: "Bulgaria" },
  { alpha2: "BF", alpha3: "BFA", nameEn: "Burkina Faso", nameEs: "Burkina Faso" },
  { alpha2: "BI", alpha3: "BDI", nameEn: "Burundi", nameEs: "Burundi" },
  { alpha2: "CV", alpha3: "CPV", nameEn: "Cabo Verde", nameEs: "Cabo Verde" },
  { alpha2: "KH", alpha3: "KHM", nameEn: "Cambodia", nameEs: "Camboya" },
  { alpha2: "CM", alpha3: "CMR", nameEn: "Cameroon", nameEs: "Camerún" },
  { alpha2: "CA", alpha3: "CAN", nameEn: "Canada", nameEs: "Canadá" },
  { alpha2: "KY", alpha3: "CYM", nameEn: "Cayman Islands", nameEs: "Islas Caimán" },
  { alpha2: "CF", alpha3: "CAF", nameEn: "Central African Republic", nameEs: "República Centroafricana" },
  { alpha2: "TD", alpha3: "TCD", nameEn: "Chad", nameEs: "Chad" },
  { alpha2: "CL", alpha3: "CHL", nameEn: "Chile", nameEs: "Chile" },
  { alpha2: "CN", alpha3: "CHN", nameEn: "China", nameEs: "China" },
  { alpha2: "CX", alpha3: "CXR", nameEn: "Christmas Island", nameEs: "Isla de Navidad" },
  { alpha2: "CC", alpha3: "CCK", nameEn: "Cocos (Keeling) Islands", nameEs: "Islas Cocos" },
  { alpha2: "CO", alpha3: "COL", nameEn: "Colombia", nameEs: "Colombia" },
  { alpha2: "KM", alpha3: "COM", nameEn: "Comoros", nameEs: "Comoras" },
  { alpha2: "CG", alpha3: "COG", nameEn: "Congo", nameEs: "Congo" },
  { alpha2: "CD", alpha3: "COD", nameEn: "Congo, Democratic Republic of the", nameEs: "República Democrática del Congo" },
  { alpha2: "CK", alpha3: "COK", nameEn: "Cook Islands", nameEs: "Islas Cook" },
  { alpha2: "CR", alpha3: "CRI", nameEn: "Costa Rica", nameEs: "Costa Rica" },
  { alpha2: "CI", alpha3: "CIV", nameEn: "Côte d'Ivoire", nameEs: "Costa de Marfil" },
  { alpha2: "HR", alpha3: "HRV", nameEn: "Croatia", nameEs: "Croacia" },
  { alpha2: "CU", alpha3: "CUB", nameEn: "Cuba", nameEs: "Cuba" },
  { alpha2: "CW", alpha3: "CUW", nameEn: "Curaçao", nameEs: "Curazao" },
  { alpha2: "CY", alpha3: "CYP", nameEn: "Cyprus", nameEs: "Chipre" },
  { alpha2: "CZ", alpha3: "CZE", nameEn: "Czechia", nameEs: "Chequia" },
  { alpha2: "DK", alpha3: "DNK", nameEn: "Denmark", nameEs: "Dinamarca" },
  { alpha2: "DJ", alpha3: "DJI", nameEn: "Djibouti", nameEs: "Yibuti" },
  { alpha2: "DM", alpha3: "DMA", nameEn: "Dominica", nameEs: "Dominica" },
  { alpha2: "DO", alpha3: "DOM", nameEn: "Dominican Republic", nameEs: "República Dominicana" },
  { alpha2: "EC", alpha3: "ECU", nameEn: "Ecuador", nameEs: "Ecuador" },
  { alpha2: "EG", alpha3: "EGY", nameEn: "Egypt", nameEs: "Egipto" },
  { alpha2: "SV", alpha3: "SLV", nameEn: "El Salvador", nameEs: "El Salvador" },
  { alpha2: "GQ", alpha3: "GNQ", nameEn: "Equatorial Guinea", nameEs: "Guinea Ecuatorial" },
  { alpha2: "ER", alpha3: "ERI", nameEn: "Eritrea", nameEs: "Eritrea" },
  { alpha2: "EE", alpha3: "EST", nameEn: "Estonia", nameEs: "Estonia" },
  { alpha2: "SZ", alpha3: "SWZ", nameEn: "Eswatini", nameEs: "Esuatini" },
  { alpha2: "ET", alpha3: "ETH", nameEn: "Ethiopia", nameEs: "Etiopía" },
  { alpha2: "FK", alpha3: "FLK", nameEn: "Falkland Islands (Malvinas)", nameEs: "Islas Malvinas" },
  { alpha2: "FO", alpha3: "FRO", nameEn: "Faroe Islands", nameEs: "Islas Feroe" },
  { alpha2: "FJ", alpha3: "FJI", nameEn: "Fiji", nameEs: "Fiyi" },
  { alpha2: "FI", alpha3: "FIN", nameEn: "Finland", nameEs: "Finlandia" },
  { alpha2: "FR", alpha3: "FRA", nameEn: "France", nameEs: "Francia" },
  { alpha2: "GF", alpha3: "GUF", nameEn: "French Guiana", nameEs: "Guayana Francesa" },
  { alpha2: "PF", alpha3: "PYF", nameEn: "French Polynesia", nameEs: "Polinesia Francesa" },
  { alpha2: "TF", alpha3: "ATF", nameEn: "French Southern Territories", nameEs: "Territorios Australes Franceses" },
  { alpha2: "GA", alpha3: "GAB", nameEn: "Gabon", nameEs: "Gabón" },
  { alpha2: "GM", alpha3: "GMB", nameEn: "Gambia", nameEs: "Gambia" },
  { alpha2: "GE", alpha3: "GEO", nameEn: "Georgia", nameEs: "Georgia" },
  { alpha2: "DE", alpha3: "DEU", nameEn: "Germany", nameEs: "Alemania" },
  { alpha2: "GH", alpha3: "GHA", nameEn: "Ghana", nameEs: "Ghana" },
  { alpha2: "GI", alpha3: "GIB", nameEn: "Gibraltar", nameEs: "Gibraltar" },
  { alpha2: "GR", alpha3: "GRC", nameEn: "Greece", nameEs: "Grecia" },
  { alpha2: "GL", alpha3: "GRL", nameEn: "Greenland", nameEs: "Groenlandia" },
  { alpha2: "GD", alpha3: "GRD", nameEn: "Grenada", nameEs: "Granada" },
  { alpha2: "GP", alpha3: "GLP", nameEn: "Guadeloupe", nameEs: "Guadalupe" },
  { alpha2: "GU", alpha3: "GUM", nameEn: "Guam", nameEs: "Guam" },
  { alpha2: "GT", alpha3: "GTM", nameEn: "Guatemala", nameEs: "Guatemala" },
  { alpha2: "GG", alpha3: "GGY", nameEn: "Guernsey", nameEs: "Guernsey" },
  { alpha2: "GN", alpha3: "GIN", nameEn: "Guinea", nameEs: "Guinea" },
  { alpha2: "GW", alpha3: "GNB", nameEn: "Guinea-Bissau", nameEs: "Guinea-Bisáu" },
  { alpha2: "GY", alpha3: "GUY", nameEn: "Guyana", nameEs: "Guyana" },
  { alpha2: "HT", alpha3: "HTI", nameEn: "Haiti", nameEs: "Haití" },
  { alpha2: "HM", alpha3: "HMD", nameEn: "Heard Island and McDonald Islands", nameEs: "Islas Heard y McDonald" },
  { alpha2: "VA", alpha3: "VAT", nameEn: "Holy See", nameEs: "Santa Sede" },
  { alpha2: "HN", alpha3: "HND", nameEn: "Honduras", nameEs: "Honduras" },
  { alpha2: "HK", alpha3: "HKG", nameEn: "Hong Kong", nameEs: "Hong Kong" },
  { alpha2: "HU", alpha3: "HUN", nameEn: "Hungary", nameEs: "Hungría" },
  { alpha2: "IS", alpha3: "ISL", nameEn: "Iceland", nameEs: "Islandia" },
  { alpha2: "IN", alpha3: "IND", nameEn: "India", nameEs: "India" },
  { alpha2: "ID", alpha3: "IDN", nameEn: "Indonesia", nameEs: "Indonesia" },
  { alpha2: "IR", alpha3: "IRN", nameEn: "Iran", nameEs: "Irán" },
  { alpha2: "IQ", alpha3: "IRQ", nameEn: "Iraq", nameEs: "Irak" },
  { alpha2: "IE", alpha3: "IRL", nameEn: "Ireland", nameEs: "Irlanda" },
  { alpha2: "IM", alpha3: "IMN", nameEn: "Isle of Man", nameEs: "Isla de Man" },
  { alpha2: "IL", alpha3: "ISR", nameEn: "Israel", nameEs: "Israel" },
  { alpha2: "IT", alpha3: "ITA", nameEn: "Italy", nameEs: "Italia" },
  { alpha2: "JM", alpha3: "JAM", nameEn: "Jamaica", nameEs: "Jamaica" },
  { alpha2: "JP", alpha3: "JPN", nameEn: "Japan", nameEs: "Japón" },
  { alpha2: "JE", alpha3: "JEY", nameEn: "Jersey", nameEs: "Jersey" },
  { alpha2: "JO", alpha3: "JOR", nameEn: "Jordan", nameEs: "Jordania" },
  { alpha2: "KZ", alpha3: "KAZ", nameEn: "Kazakhstan", nameEs: "Kazajistán" },
  { alpha2: "KE", alpha3: "KEN", nameEn: "Kenya", nameEs: "Kenia" },
  { alpha2: "KI", alpha3: "KIR", nameEn: "Kiribati", nameEs: "Kiribati" },
  { alpha2: "KP", alpha3: "PRK", nameEn: "Korea (Democratic People's Republic of)", nameEs: "Corea del Norte" },
  { alpha2: "KR", alpha3: "KOR", nameEn: "Korea, Republic of", nameEs: "Corea del Sur" },
  { alpha2: "KW", alpha3: "KWT", nameEn: "Kuwait", nameEs: "Kuwait" },
  { alpha2: "KG", alpha3: "KGZ", nameEn: "Kyrgyzstan", nameEs: "Kirguistán" },
  { alpha2: "LA", alpha3: "LAO", nameEn: "Lao People's Democratic Republic", nameEs: "Laos" },
  { alpha2: "LV", alpha3: "LVA", nameEn: "Latvia", nameEs: "Letonia" },
  { alpha2: "LB", alpha3: "LBN", nameEn: "Lebanon", nameEs: "Líbano" },
  { alpha2: "LS", alpha3: "LSO", nameEn: "Lesotho", nameEs: "Lesoto" },
  { alpha2: "LR", alpha3: "LBR", nameEn: "Liberia", nameEs: "Liberia" },
  { alpha2: "LY", alpha3: "LBY", nameEn: "Libya", nameEs: "Libia" },
  { alpha2: "LI", alpha3: "LIE", nameEn: "Liechtenstein", nameEs: "Liechtenstein" },
  { alpha2: "LT", alpha3: "LTU", nameEn: "Lithuania", nameEs: "Lituania" },
  { alpha2: "LU", alpha3: "LUX", nameEn: "Luxembourg", nameEs: "Luxemburgo" },
  { alpha2: "MO", alpha3: "MAC", nameEn: "Macao", nameEs: "Macao" },
  { alpha2: "MG", alpha3: "MDG", nameEn: "Madagascar", nameEs: "Madagascar" },
  { alpha2: "MW", alpha3: "MWI", nameEn: "Malawi", nameEs: "Malaui" },
  { alpha2: "MY", alpha3: "MYS", nameEn: "Malaysia", nameEs: "Malasia" },
  { alpha2: "MV", alpha3: "MDV", nameEn: "Maldives", nameEs: "Maldivas" },
  { alpha2: "ML", alpha3: "MLI", nameEn: "Mali", nameEs: "Malí" },
  { alpha2: "MT", alpha3: "MLT", nameEn: "Malta", nameEs: "Malta" },
  { alpha2: "MH", alpha3: "MHL", nameEn: "Marshall Islands", nameEs: "Islas Marshall" },
  { alpha2: "MQ", alpha3: "MTQ", nameEn: "Martinique", nameEs: "Martinica" },
  { alpha2: "MR", alpha3: "MRT", nameEn: "Mauritania", nameEs: "Mauritania" },
  { alpha2: "MU", alpha3: "MUS", nameEn: "Mauritius", nameEs: "Mauricio" },
  { alpha2: "YT", alpha3: "MYT", nameEn: "Mayotte", nameEs: "Mayotte" },
  { alpha2: "MX", alpha3: "MEX", nameEn: "Mexico", nameEs: "México" },
  { alpha2: "FM", alpha3: "FSM", nameEn: "Micronesia (Federated States of)", nameEs: "Micronesia" },
  { alpha2: "MD", alpha3: "MDA", nameEn: "Moldova, Republic of", nameEs: "Moldavia" },
  { alpha2: "MC", alpha3: "MCO", nameEn: "Monaco", nameEs: "Mónaco" },
  { alpha2: "MN", alpha3: "MNG", nameEn: "Mongolia", nameEs: "Mongolia" },
  { alpha2: "ME", alpha3: "MNE", nameEn: "Montenegro", nameEs: "Montenegro" },
  { alpha2: "MS", alpha3: "MSR", nameEn: "Montserrat", nameEs: "Montserrat" },
  { alpha2: "MA", alpha3: "MAR", nameEn: "Morocco", nameEs: "Marruecos" },
  { alpha2: "MZ", alpha3: "MOZ", nameEn: "Mozambique", nameEs: "Mozambique" },
  { alpha2: "MM", alpha3: "MMR", nameEn: "Myanmar", nameEs: "Myanmar" },
  { alpha2: "NA", alpha3: "NAM", nameEn: "Namibia", nameEs: "Namibia" },
  { alpha2: "NR", alpha3: "NRU", nameEn: "Nauru", nameEs: "Nauru" },
  { alpha2: "NP", alpha3: "NPL", nameEn: "Nepal", nameEs: "Nepal" },
  { alpha2: "NL", alpha3: "NLD", nameEn: "Netherlands", nameEs: "Países Bajos" },
  { alpha2: "NC", alpha3: "NCL", nameEn: "New Caledonia", nameEs: "Nueva Caledonia" },
  { alpha2: "NZ", alpha3: "NZL", nameEn: "New Zealand", nameEs: "Nueva Zelanda" },
  { alpha2: "NI", alpha3: "NIC", nameEn: "Nicaragua", nameEs: "Nicaragua" },
  { alpha2: "NE", alpha3: "NER", nameEn: "Niger", nameEs: "Níger" },
  { alpha2: "NG", alpha3: "NGA", nameEn: "Nigeria", nameEs: "Nigeria" },
  { alpha2: "NU", alpha3: "NIU", nameEn: "Niue", nameEs: "Niue" },
  { alpha2: "NF", alpha3: "NFK", nameEn: "Norfolk Island", nameEs: "Isla Norfolk" },
  { alpha2: "MK", alpha3: "MKD", nameEn: "North Macedonia", nameEs: "Macedonia del Norte" },
  { alpha2: "MP", alpha3: "MNP", nameEn: "Northern Mariana Islands", nameEs: "Islas Marianas del Norte" },
  { alpha2: "NO", alpha3: "NOR", nameEn: "Norway", nameEs: "Noruega" },
  { alpha2: "OM", alpha3: "OMN", nameEn: "Oman", nameEs: "Omán" },
  { alpha2: "PK", alpha3: "PAK", nameEn: "Pakistan", nameEs: "Pakistán" },
  { alpha2: "PW", alpha3: "PLW", nameEn: "Palau", nameEs: "Palaos" },
  { alpha2: "PS", alpha3: "PSE", nameEn: "Palestine, State of", nameEs: "Palestina" },
  { alpha2: "PA", alpha3: "PAN", nameEn: "Panama", nameEs: "Panamá" },
  { alpha2: "PG", alpha3: "PNG", nameEn: "Papua New Guinea", nameEs: "Papúa Nueva Guinea" },
  { alpha2: "PY", alpha3: "PRY", nameEn: "Paraguay", nameEs: "Paraguay" },
  { alpha2: "PE", alpha3: "PER", nameEn: "Peru", nameEs: "Perú" },
  { alpha2: "PH", alpha3: "PHL", nameEn: "Philippines", nameEs: "Filipinas" },
  { alpha2: "PN", alpha3: "PCN", nameEn: "Pitcairn", nameEs: "Islas Pitcairn" },
  { alpha2: "PL", alpha3: "POL", nameEn: "Poland", nameEs: "Polonia" },
  { alpha2: "PT", alpha3: "PRT", nameEn: "Portugal", nameEs: "Portugal" },
  { alpha2: "PR", alpha3: "PRI", nameEn: "Puerto Rico", nameEs: "Puerto Rico" },
  { alpha2: "QA", alpha3: "QAT", nameEn: "Qatar", nameEs: "Catar" },
  { alpha2: "RE", alpha3: "REU", nameEn: "Réunion", nameEs: "Reunión" },
  { alpha2: "RO", alpha3: "ROU", nameEn: "Romania", nameEs: "Rumania" },
  { alpha2: "RU", alpha3: "RUS", nameEn: "Russian Federation", nameEs: "Rusia" },
  { alpha2: "RW", alpha3: "RWA", nameEn: "Rwanda", nameEs: "Ruanda" },
  { alpha2: "BL", alpha3: "BLM", nameEn: "Saint Barthélemy", nameEs: "San Bartolomé" },
  { alpha2: "SH", alpha3: "SHN", nameEn: "Saint Helena, Ascension and Tristan da Cunha", nameEs: "Santa Elena, Ascensión y Tristán de Acuña" },
  { alpha2: "KN", alpha3: "KNA", nameEn: "Saint Kitts and Nevis", nameEs: "San Cristóbal y Nieves" },
  { alpha2: "LC", alpha3: "LCA", nameEn: "Saint Lucia", nameEs: "Santa Lucía" },
  { alpha2: "MF", alpha3: "MAF", nameEn: "Saint Martin (French part)", nameEs: "San Martín (parte francesa)" },
  { alpha2: "PM", alpha3: "SPM", nameEn: "Saint Pierre and Miquelon", nameEs: "San Pedro y Miquelón" },
  { alpha2: "VC", alpha3: "VCT", nameEn: "Saint Vincent and the Grenadines", nameEs: "San Vicente y las Granadinas" },
  { alpha2: "WS", alpha3: "WSM", nameEn: "Samoa", nameEs: "Samoa" },
  { alpha2: "SM", alpha3: "SMR", nameEn: "San Marino", nameEs: "San Marino" },
  { alpha2: "ST", alpha3: "STP", nameEn: "Sao Tome and Principe", nameEs: "Santo Tomé y Príncipe" },
  { alpha2: "SA", alpha3: "SAU", nameEn: "Saudi Arabia", nameEs: "Arabia Saudita" },
  { alpha2: "SN", alpha3: "SEN", nameEn: "Senegal", nameEs: "Senegal" },
  { alpha2: "RS", alpha3: "SRB", nameEn: "Serbia", nameEs: "Serbia" },
  { alpha2: "SC", alpha3: "SYC", nameEn: "Seychelles", nameEs: "Seychelles" },
  { alpha2: "SL", alpha3: "SLE", nameEn: "Sierra Leone", nameEs: "Sierra Leona" },
  { alpha2: "SG", alpha3: "SGP", nameEn: "Singapore", nameEs: "Singapur" },
  { alpha2: "SX", alpha3: "SXM", nameEn: "Sint Maarten (Dutch part)", nameEs: "San Martín (parte neerlandesa)" },
  { alpha2: "SK", alpha3: "SVK", nameEn: "Slovakia", nameEs: "Eslovaquia" },
  { alpha2: "SI", alpha3: "SVN", nameEn: "Slovenia", nameEs: "Eslovenia" },
  { alpha2: "SB", alpha3: "SLB", nameEn: "Solomon Islands", nameEs: "Islas Salomón" },
  { alpha2: "SO", alpha3: "SOM", nameEn: "Somalia", nameEs: "Somalia" },
  { alpha2: "ZA", alpha3: "ZAF", nameEn: "South Africa", nameEs: "Sudáfrica" },
  { alpha2: "GS", alpha3: "SGS", nameEn: "South Georgia and the South Sandwich Islands", nameEs: "Georgia del Sur y las Islas Sandwich del Sur" },
  { alpha2: "SS", alpha3: "SSD", nameEn: "South Sudan", nameEs: "Sudán del Sur" },
  { alpha2: "ES", alpha3: "ESP", nameEn: "Spain", nameEs: "España" },
  { alpha2: "LK", alpha3: "LKA", nameEn: "Sri Lanka", nameEs: "Sri Lanka" },
  { alpha2: "SD", alpha3: "SDN", nameEn: "Sudan", nameEs: "Sudán" },
  { alpha2: "SR", alpha3: "SUR", nameEn: "Suriname", nameEs: "Surinam" },
  { alpha2: "SJ", alpha3: "SJM", nameEn: "Svalbard and Jan Mayen", nameEs: "Svalbard y Jan Mayen" },
  { alpha2: "SE", alpha3: "SWE", nameEn: "Sweden", nameEs: "Suecia" },
  { alpha2: "CH", alpha3: "CHE", nameEn: "Switzerland", nameEs: "Suiza" },
  { alpha2: "SY", alpha3: "SYR", nameEn: "Syrian Arab Republic", nameEs: "Siria" },
  { alpha2: "TW", alpha3: "TWN", nameEn: "Taiwan", nameEs: "Taiwán" },
  { alpha2: "TJ", alpha3: "TJK", nameEn: "Tajikistan", nameEs: "Tayikistán" },
  { alpha2: "TZ", alpha3: "TZA", nameEn: "Tanzania, United Republic of", nameEs: "Tanzania" },
  { alpha2: "TH", alpha3: "THA", nameEn: "Thailand", nameEs: "Tailandia" },
  { alpha2: "TL", alpha3: "TLS", nameEn: "Timor-Leste", nameEs: "Timor Oriental" },
  { alpha2: "TG", alpha3: "TGO", nameEn: "Togo", nameEs: "Togo" },
  { alpha2: "TK", alpha3: "TKL", nameEn: "Tokelau", nameEs: "Tokelau" },
  { alpha2: "TO", alpha3: "TON", nameEn: "Tonga", nameEs: "Tonga" },
  { alpha2: "TT", alpha3: "TTO", nameEn: "Trinidad and Tobago", nameEs: "Trinidad y Tobago" },
  { alpha2: "TN", alpha3: "TUN", nameEn: "Tunisia", nameEs: "Túnez" },
  { alpha2: "TR", alpha3: "TUR", nameEn: "Türkiye", nameEs: "Turquía" },
  { alpha2: "TM", alpha3: "TKM", nameEn: "Turkmenistan", nameEs: "Turkmenistán" },
  { alpha2: "TC", alpha3: "TCA", nameEn: "Turks and Caicos Islands", nameEs: "Islas Turcas y Caicos" },
  { alpha2: "TV", alpha3: "TUV", nameEn: "Tuvalu", nameEs: "Tuvalu" },
  { alpha2: "UG", alpha3: "UGA", nameEn: "Uganda", nameEs: "Uganda" },
  { alpha2: "UA", alpha3: "UKR", nameEn: "Ukraine", nameEs: "Ucrania" },
  { alpha2: "AE", alpha3: "ARE", nameEn: "United Arab Emirates", nameEs: "Emiratos Árabes Unidos" },
  { alpha2: "GB", alpha3: "GBR", nameEn: "United Kingdom", nameEs: "Reino Unido" },
  { alpha2: "US", alpha3: "USA", nameEn: "United States", nameEs: "Estados Unidos" },
  { alpha2: "UM", alpha3: "UMI", nameEn: "United States Minor Outlying Islands", nameEs: "Islas Ultramarinas Menores de los Estados Unidos" },
  { alpha2: "UY", alpha3: "URY", nameEn: "Uruguay", nameEs: "Uruguay" },
  { alpha2: "UZ", alpha3: "UZB", nameEn: "Uzbekistan", nameEs: "Uzbekistán" },
  { alpha2: "VU", alpha3: "VUT", nameEn: "Vanuatu", nameEs: "Vanuatu" },
  { alpha2: "VE", alpha3: "VEN", nameEn: "Venezuela", nameEs: "Venezuela" },
  { alpha2: "VN", alpha3: "VNM", nameEn: "Viet Nam", nameEs: "Vietnam" },
  { alpha2: "VG", alpha3: "VGB", nameEn: "Virgin Islands (British)", nameEs: "Islas Vírgenes Británicas" },
  { alpha2: "VI", alpha3: "VIR", nameEn: "Virgin Islands (U.S.)", nameEs: "Islas Vírgenes de los Estados Unidos" },
  { alpha2: "WF", alpha3: "WLF", nameEn: "Wallis and Futuna", nameEs: "Wallis y Futuna" },
  { alpha2: "EH", alpha3: "ESH", nameEn: "Western Sahara", nameEs: "Sahara Occidental" },
  { alpha2: "YE", alpha3: "YEM", nameEn: "Yemen", nameEs: "Yemen" },
  { alpha2: "ZM", alpha3: "ZMB", nameEn: "Zambia", nameEs: "Zambia" },
  { alpha2: "ZW", alpha3: "ZWE", nameEn: "Zimbabwe", nameEs: "Zimbabue" },
];

/** The locale-appropriate display name for a country. */
export function countryName(country: Country, locale: string): string {
  return locale.startsWith("es") ? country.nameEs : country.nameEn;
}

/** Entries sorted by their name in the active locale. */
export function countriesSortedFor(locale: string): Country[] {
  const collator = new Intl.Collator(locale.startsWith("es") ? "es" : "en");
  return [...COUNTRIES].sort((a, b) =>
    collator.compare(countryName(a, locale), countryName(b, locale)),
  );
}

/** Resolve an entry by its alpha-2 code (case-insensitive), or null. */
export function countryByAlpha2(alpha2: string): Country | null {
  const key = alpha2.trim().toUpperCase();
  return COUNTRIES.find((c) => c.alpha2 === key) ?? null;
}

/** Resolve an entry by its alpha-3 code (case-insensitive), or null. */
export function countryByAlpha3(alpha3: string): Country | null {
  const key = alpha3.trim().toUpperCase();
  return COUNTRIES.find((c) => c.alpha3 === key) ?? null;
}
