/**
 * Spanish translations — entities namespace
 *
 * This locale namespace carries the Spanish strings for the entities
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Entities follow ISAAR(CPF), so the labels
 * stay close to the standard's preferred Spanish phrasing.
 *
 * @version v0.3.0
 */
export default {
  // Page
  title: "Entidades",
  primaryCta: "Agregar entidad",

  // Form
  createTitle: "Nueva entidad",
  createSubmit: "Crear entidad",
  editSave: "Guardar cambios",
  editButton: "Editar entidad",
  discardButton: "Descartar cambios",
  backButton: "Volver a entidades",

  // Delete
  deleteButton: "Eliminar entidad",
  deleteTitle: "Eliminar entidad",
  deleteBody:
    "¿Está seguro de que desea eliminar {{name}}? Esta acción no se puede deshacer.",
  deleteBlocked: "No se puede eliminar — {{count}} descripciones vinculadas",
  cascadeWarning: "Esta entidad tiene {{count}} descripciones vinculadas.",
  cascadeExamples: "Ejemplos:",

  // Search
  searchPlaceholder: "Buscar entidades...",
  advancedToggle: "Búsqueda avanzada",
  advancedHide: "Ocultar búsqueda avanzada",
  advancedActive: "Búsqueda avanzada activa",
  advancedClear: "Limpiar",
  advancedSearch: "Buscar",

  // Filter
  allTypes: "Todos los tipos",
  person: "Persona",
  family: "Familia",
  corporate: "Entidad corporativa",
  showMerged: "Mostrar combinados",

  // Pagination
  previous: "Anterior",
  next: "Siguiente",
  showing: "Mostrando {{count}} entidades",

  // Columns
  columnToggle: "Columnas",

  // Merge
  mergeButton: "Combinar",
  mergeTitle: "Combinar entidad",
  mergeSearch: "Buscar registro destino...",
  mergeReassignTitle: "Reasignar vínculos",
  mergeReassignSubtitle:
    "{{name}} tiene {{count}} descripciones vinculadas",
  mergeConfirm: "Confirmar combinación",
  mergeCancel: "Cancelar",
  mergedBanner: "Este registro fue combinado en {{target}}.",
  mergedBannerLink: "Ver registro destino",
  mergedSuffix: "(combinado)",

  // Split
  splitButton: "Dividir",
  splitTitle: "Dividir entidad",
  splitSubtitle:
    "Se creará un nuevo registro con los datos de {{name}}. Seleccione los vínculos que deben moverse al nuevo registro.",
  splitConfirm: "Confirmar división",
  splitCancel: "Cancelar",
  loadMore: "Cargar más",
  selectAll: "Seleccionar todos",
  deselectAll: "Deseleccionar todos",

  // Success
  successCreated: "Entidad creada.",
  successUpdated: "Entidad actualizada.",
  successDeleted: "Entidad eliminada.",
  successMerged: "Entidad combinada.",
  successSplit: "Entidad dividida.",

  // Error
  errorGeneric: "Ocurrió un error. Intenta de nuevo.",
  errorRequired: "Este campo es obligatorio.",
  errorInvalidLod: "Formato inválido.",
  errorDuplicateCode: "Ya existe una entidad con ese código.",

  // Field labels
  "field.displayName": "Nombre para mostrar",
  "field.sortName": "Nombre para ordenar",
  "field.surname": "Apellido",
  "field.givenName": "Nombre de pila",
  "field.honorific": "Título honorífico",
  "field.entityType": "Tipo de entidad",
  "field.entityCode": "Código de entidad",
  "field.nameVariants": "Variantes del nombre",
  "field.datesOfExistence": "Fechas de existencia",
  "field.dateStart": "Fecha de inicio",
  "field.dateEnd": "Fecha de fin",
  "field.history": "Historia",
  "field.primaryFunction": "Función principal",
  primary_function_placeholder: "Buscar o escribir una función...",
  "field.legalStatus": "Estatus legal",
  "field.functions": "Funciones",
  "field.mergedInto": "Combinado en",
  "field.sources": "Fuentes",
  "field.wikidataId": "Wikidata",
  "field.viafId": "VIAF",
  "field.createdAt": "Creado",
  "field.updatedAt": "Actualizado",

  // Section headings
  sectionIdentity: "Área de identidad",
  sectionDescription: "Área de descripción",
  sectionRelationships: "Relaciones",
  sectionControl: "Control",

  // Misc
  autoGenerated: "Se genera automáticamente.",
  addVariant: "Agregar variante",
  breadcrumbNew: "Nueva entidad",
  emptyHeading: "No hay entidades",
  emptyBody:
    "Agrega la primera entidad o importa registros de autoridad existentes.",
  goBack: "Volver",

  // Draft/changelog
  commit_note_placeholder: "Nota sobre los cambios (opcional)",
  autosave_saving: "Guardando...",
  autosave_saved: "Borrador guardado",
  conflict_banner:
    "{{name}} tiene cambios sin guardar desde {{time}}.",
  overwrite_confirm:
    "Este registro fue modificado por {{name}} a las {{time}}. ¿Desea sobreescribir?",
  overwrite_button: "Sobreescribir",
  overwrite_cancel: "Cancelar",

  // Linked descriptions
  linked_descriptions: "Descripciones vinculadas",
  no_linked_descriptions: "Sin descripciones vinculadas",
  add_description_link: "Vincular una descripción",
  search_descriptions: "Buscar descripciones...",
  select_role: "Seleccionar rol",
  link_button: "Vincular",
  edit_link: "Editar vínculo",
  remove_link: "Quitar vínculo",
  remove_link_confirm: "¿Quitar este vínculo?",
  duplicate_link_error: "Esta descripción ya está vinculada con este rol",
  role_note_label: "Nota del rol",
  sequence_label: "Secuencia",
  honorific_label: "Honorífico",
  function_label: "Función",
  name_as_recorded_label: "Nombre registrado",

  // Entity roles (must match ENTITY_ROLES in lib/validation/enums.ts)
  role_creator: "Creador",
  role_author: "Autor",
  role_editor: "Editor",
  role_publisher: "Editor (publicación)",
  role_sender: "Remitente",
  role_recipient: "Destinatario",
  role_mentioned: "Mencionado",
  role_subject: "Tema",
  role_scribe: "Escribano",
  role_witness: "Testigo",
  role_notary: "Notario",
  role_photographer: "Fotógrafo",
  role_artist: "Artista",
  role_plaintiff: "Demandante",
  role_defendant: "Demandado",
  role_petitioner: "Peticionario",
  role_judge: "Juez",
  role_appellant: "Apelante",
  role_official: "Funcionario",
  role_heir: "Heredero",
  role_albacea: "Albacea",
  role_spouse: "Cónyuge",
  role_victim: "Víctima",
  role_grantor: "Otorgante",
  role_donor: "Donante",
  role_seller: "Vendedor",
  role_buyer: "Comprador",
  role_mortgagor: "Deudor hipotecario",
  role_mortgagee: "Acreedor hipotecario",
  role_creditor: "Acreedor",
  role_debtor: "Deudor",
} as const;
