/**
 * Spanish translations — places namespace
 *
 * This locale namespace carries the Spanish strings for the places
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Places follow the Linked Places conventions
 * the rest of the entities surface uses.
 *
 * @version v0.4.3
 */
export default {
  // Page
  title: "Lugares",
  primaryCta: "Agregar lugar",

  // Form
  createTitle: "Nuevo lugar",
  createSubmit: "Crear lugar",
  editSave: "Guardar cambios",
  editButton: "Editar lugar",
  discardButton: "Descartar cambios",
  backButton: "Volver a lugares",

  // Delete
  deleteButton: "Eliminar lugar",
  deleteTitle: "Eliminar lugar",
  deleteBody:
    "¿Está seguro de que desea eliminar {{name}}? Esta acción no se puede deshacer.",
  deleteBlocked: "No se puede eliminar — {{count}} descripciones vinculadas",
  cascadeWarning: "Este lugar tiene {{count}} descripciones vinculadas.",
  cascadeExamples: "Ejemplos:",

  // Search
  searchPlaceholder: "Buscar lugares...",
  advancedToggle: "Búsqueda avanzada",
  advancedHide: "Ocultar búsqueda avanzada",
  advancedActive: "Búsqueda avanzada activa",
  advancedClear: "Limpiar",
  advancedSearch: "Buscar",

  // Filter
  allTypes: "Todos los tipos",
  country: "País",
  region: "Región",
  department: "Departamento",
  province: "Provincia",
  partido: "Partido",
  city: "Ciudad",
  town: "Pueblo",
  parish: "Parroquia",
  hacienda: "Hacienda",
  mine: "Mina",
  river: "Río",
  other: "Otro",
  showMerged: "Mostrar combinados",

  // Pagination
  previous: "Anterior",
  next: "Siguiente",
  showing: "Mostrando {{count}} lugares",

  // Columns
  columnToggle: "Columnas",

  // Merge
  mergeButton: "Combinar",
  mergeTitle: "Combinar lugar",
  mergeSearch: "Buscar registro destino...",
  mergeReassignTitle: "Reasignar vínculos",
  mergeReassignSubtitle:
    "{{name}} tiene {{count}} descripciones vinculadas",
  mergeConfirm: "Confirmar combinación",
  mergeCancel: "Cancelar",
  mergedBanner: "Este registro fue combinado en {{target}}.",
  mergedBannerLink: "Ver registro destino",
  mergedSuffix: "(combinado)",

  // Split
  splitButton: "Dividir",
  splitTitle: "Dividir lugar",
  splitSubtitle:
    "Se creará un nuevo registro con los datos de {{name}}. Seleccione los vínculos que deben moverse al nuevo registro.",
  splitConfirm: "Confirmar división",
  splitCancel: "Cancelar",
  loadMore: "Cargar más",
  selectAll: "Seleccionar todos",
  deselectAll: "Deseleccionar todos",

  // Success
  successCreated: "Lugar creado.",
  successUpdated: "Lugar actualizado.",
  successDeleted: "Lugar eliminado.",
  successMerged: "Lugar combinado.",
  successSplit: "Lugar dividido.",

  // Error
  errorGeneric: "Ocurrió un error. Intenta de nuevo.",
  errorRequired: "Este campo es obligatorio.",
  errorInvalidLod: "Formato inválido.",
  errorDuplicateCode: "Ya existe un lugar con ese código.",

  // Field labels
  "field.label": "Nombre",
  "field.displayName": "Nombre para mostrar",
  "field.placeCode": "Código de lugar",
  "field.placeType": "Tipo de lugar",
  "field.nameVariants": "Variantes del nombre",
  "field.parentId": "Lugar padre",
  "field.historicalGobernacion": "Gobernación",
  "field.historicalPartido": "Partido",
  "field.historicalRegion": "Región",
  "field.countryCode": "Código de país",
  "field.adminLevel1": "Nivel administrativo 1",
  "field.adminLevel2": "Nivel administrativo 2",
  "field.latitude": "Latitud",
  "field.longitude": "Longitud",
  "field.coordinatePrecision": "Precisión de coordenadas",
  "field.mergedInto": "Combinado en",
  "field.tgnId": "TGN",
  "field.hgisId": "HGIS",
  "field.whgId": "WHG",
  "field.wikidataId": "Wikidata",
  "field.notes": "Notas",
  "field.internalNotes": "Notas internas",
  "field.createdAt": "Creado",
  "field.updatedAt": "Actualizado",

  // Section headings
  sectionIdentity: "Identidad",
  sectionHistorical: "Contexto histórico",
  sectionGeography: "Geografía moderna y LOD",
  sectionControl: "Control",
  sectionNotes: "Notas",
  sectionInternalNotes: "Notas internas",
  internalBadge: "Interna",

  // Coordinate precision
  precisionExact: "Exacta",
  precisionApproximate: "Aproximada",
  precisionCentroid: "Centroide",
  precisionUncertain: "Incierta",

  // Misc
  autoGenerated: "Se genera automáticamente.",
  addVariant: "Agregar variante",
  breadcrumbNew: "Nuevo lugar",
  emptyHeading: "No hay lugares",
  emptyBody:
    "Agrega el primer lugar o importa registros de autoridad existentes.",
  goBack: "Volver",

  // Draft/changelog
  commit_note_placeholder: "Nota sobre los cambios (opcional)",
  autosave_saving: "Guardando...",
  autosave_saved: "Borrador guardado",
  conflict_banner:
    "{{name}} tiene cambios sin guardar desde {{time}}.",
  overwrite_confirm:
    "Este registro fue modificado por {{name}} a las {{time}}. ¿Desea sobreescribir?",
  overwrite_button: "Sobreescribir",
  overwrite_cancel: "Cancelar",

  // Linked descriptions
  linked_descriptions: "Descripciones vinculadas",
  no_linked_descriptions: "Sin descripciones vinculadas",
  add_description_link: "Vincular una descripción",
  search_descriptions: "Buscar descripciones...",
  select_role: "Seleccionar rol",
  link_button: "Vincular",
  edit_link: "Editar vínculo",
  remove_link: "Quitar vínculo",
  remove_link_confirm: "¿Quitar este vínculo?",
  duplicate_link_error: "Esta descripción ya está vinculada con este rol",
  role_note_label: "Nota del rol",

  // Place roles
  role_created: "Creado",
  role_subject: "Tema",
  role_mentioned: "Mencionado",
  role_sent_from: "Enviado desde",
  role_sent_to: "Recibido en",
  role_published: "Publicado",
  role_venue: "Lugar",
  // Coordinates column + geocoding worklist (design surface 7)
  "field.coordinates": "Coordenadas",
  missingCoordsChip: "Sin coordenadas",
  reviewCoordsChip: "Coordenadas por revisar",
  reviewBadge: "por revisar",
  missingCoordsNotice:
    "{{count}} lugares aún no tienen coordenadas: este filtro es la lista de trabajo de geocodificación.",
  viewTable: "Vista de tabla",
  viewMap: "Vista de mapa",

  // Map explorer (design surface 8)
  mapNoCoordsNotice: "{{count}} lugares aún no tienen coordenadas",
  mapReview: "Revisar",
  mapFilterToggle: "Filtrar la lista según el mapa",
  mapInView: "{{count}} lugares a la vista",
  mapTotal: "{{count}} en total",
  mapEmptyTitle: "No hay lugares en esta vista",
  mapEmptyBody: "Aleja o desplaza el mapa para encontrar lugares ubicados.",
  mapOpenRecord: "Abrir registro",
  mapDescriptions: "{{count}} descripciones",
  mapZoomIn: "Acercar",
  mapZoomOut: "Alejar",

  // Map preview (design surface 9)
  previewPrecision: "Precisión · {{value}}",
  previewNoCoords: "Aún no hay coordenadas",
  previewSetCoords: "Definir coordenadas",

  // Coordinate editor (design surface 10)
  coordClickPrompt: "Haz clic en el mapa para definir la ubicación",
  coordDragHint: "Arrastra el pin para ajustar",
  coordPrecisionLabel: "Precisión",
  // Opción vacía (sin definir) del selector de precisión.
  coordPrecisionUnset: "Sin registrar",

  // Combined places surface (spec §5 — una sola página de lista y mapa)
  linkCount_one: "{{count}} vínculo",
  linkCount_other: "{{count}} vínculos",
  noPin: "sin ubicación",
  loadingMore: "Cargando…",
  listEmptyTitle: "No hay lugares en esta lista",
  listEmptyBody: "Ajusta la búsqueda o los filtros para ver lugares aquí.",
  mapDimmed:
    "El mapa queda vacío mientras el filtro de lugares sin coordenadas está activo.",
  paneList: "Lista",
  paneMap: "Mapa",
  countBrowse:
    "Mostrando {{shown}} de {{total}} lugares · {{located}} con coordenadas · {{without}} sin coordenadas",
  countMissing:
    "Mostrando {{shown}} de {{total}} lugares sin coordenadas: la lista de trabajo de geocodificación",
  countReview:
    "Mostrando {{shown}} de {{total}} lugares por revisar: coordenadas marcadas como inciertas",
  countViewport:
    "Mostrando {{shown}} de {{inView}} coincidencias a la vista · {{located}} lugares tienen coordenadas · se excluyen {{without}} sin coordenadas mientras el filtro del mapa está activo",
  countMergedSuffix_one: "· se muestra {{count}} registro combinado",
  countMergedSuffix_other: "· se muestran {{count}} registros combinados",
  extHas: "Con {{id}}",
  extMissing: "Sin {{id}}",
  extFilterAria: "Filtrar por {{id}}",
  extClearAria: "Quitar el filtro de {{id}}",
  resetFilters: "Restablecer",

  // Rediseño de la página de detalle: tarjeta LOD + búsqueda de lugares (modo edición)
  sectionLod: "Datos abiertos enlazados",
  geocodePlaceholder: "Buscar un lugar actual…",
  geocodeNoResults: "Sin resultados",
  geocodeUnavailable:
    "La búsqueda de lugares no está disponible en este momento: marca la ubicación en el mapa o escribe las coordenadas.",
} as const;
