/**
 * Spanish translations — places namespace
 *
 * This locale namespace carries the Spanish strings for the places
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Places follow the Linked Places conventions
 * the rest of the entities surface uses.
 *
 * @version v0.3.0
 */
export default {
  // Page
  title: "Lugares",
  primaryCta: "Agregar lugar",

  // Form
  createTitle: "Nuevo lugar",
  createSubmit: "Crear lugar",
  editSave: "Guardar cambios",
  editButton: "Editar lugar",
  discardButton: "Descartar cambios",
  backButton: "Volver a lugares",

  // Delete
  deleteButton: "Eliminar lugar",
  deleteTitle: "Eliminar lugar",
  deleteBody:
    "¿Está seguro de que desea eliminar {{name}}? Esta acción no se puede deshacer.",
  deleteBlocked: "No se puede eliminar — {{count}} descripciones vinculadas",
  cascadeWarning: "Este lugar tiene {{count}} descripciones vinculadas.",
  cascadeExamples: "Ejemplos:",

  // Search
  searchPlaceholder: "Buscar lugares...",
  advancedToggle: "Búsqueda avanzada",
  advancedHide: "Ocultar búsqueda avanzada",
  advancedActive: "Búsqueda avanzada activa",
  advancedClear: "Limpiar",
  advancedSearch: "Buscar",

  // Filter
  allTypes: "Todos los tipos",
  country: "País",
  region: "Región",
  department: "Departamento",
  province: "Provincia",
  partido: "Partido",
  city: "Ciudad",
  town: "Pueblo",
  parish: "Parroquia",
  hacienda: "Hacienda",
  mine: "Mina",
  river: "Río",
  other: "Otro",
  showMerged: "Mostrar combinados",

  // Pagination
  previous: "Anterior",
  next: "Siguiente",
  showing: "Mostrando {{count}} lugares",

  // Columns
  columnToggle: "Columnas",

  // Merge
  mergeButton: "Combinar",
  mergeTitle: "Combinar lugar",
  mergeSearch: "Buscar registro destino...",
  mergeReassignTitle: "Reasignar vínculos",
  mergeReassignSubtitle:
    "{{name}} tiene {{count}} descripciones vinculadas",
  mergeConfirm: "Confirmar combinación",
  mergeCancel: "Cancelar",
  mergedBanner: "Este registro fue combinado en {{target}}.",
  mergedBannerLink: "Ver registro destino",
  mergedSuffix: "(combinado)",

  // Split
  splitButton: "Dividir",
  splitTitle: "Dividir lugar",
  splitSubtitle:
    "Se creará un nuevo registro con los datos de {{name}}. Seleccione los vínculos que deben moverse al nuevo registro.",
  splitConfirm: "Confirmar división",
  splitCancel: "Cancelar",
  loadMore: "Cargar más",
  selectAll: "Seleccionar todos",
  deselectAll: "Deseleccionar todos",

  // Success
  successCreated: "Lugar creado.",
  successUpdated: "Lugar actualizado.",
  successDeleted: "Lugar eliminado.",
  successMerged: "Lugar combinado.",
  successSplit: "Lugar dividido.",

  // Error
  errorGeneric: "Ocurrió un error. Intenta de nuevo.",
  errorRequired: "Este campo es obligatorio.",
  errorInvalidLod: "Formato inválido.",
  errorDuplicateCode: "Ya existe un lugar con ese código.",

  // Field labels
  "field.label": "Nombre",
  "field.displayName": "Nombre para mostrar",
  "field.placeCode": "Código de lugar",
  "field.placeType": "Tipo de lugar",
  "field.nameVariants": "Variantes del nombre",
  "field.parentId": "Lugar padre",
  "field.historicalGobernacion": "Gobernación",
  "field.historicalPartido": "Partido",
  "field.historicalRegion": "Región",
  "field.countryCode": "Código de país",
  "field.adminLevel1": "Nivel administrativo 1",
  "field.adminLevel2": "Nivel administrativo 2",
  "field.latitude": "Latitud",
  "field.longitude": "Longitud",
  "field.coordinatePrecision": "Precisión de coordenadas",
  "field.mergedInto": "Combinado en",
  "field.tgnId": "TGN",
  "field.hgisId": "HGIS",
  "field.whgId": "WHG",
  "field.wikidataId": "Wikidata",
  "field.createdAt": "Creado",
  "field.updatedAt": "Actualizado",

  // Section headings
  sectionIdentity: "Identidad",
  sectionHistorical: "Contexto histórico",
  sectionGeography: "Geografía moderna y LOD",
  sectionControl: "Control",

  // Coordinate precision
  precisionExact: "Exacta",
  precisionApproximate: "Aproximada",
  precisionCentroid: "Centroide",

  // Misc
  autoGenerated: "Se genera automáticamente.",
  addVariant: "Agregar variante",
  breadcrumbNew: "Nuevo lugar",
  emptyHeading: "No hay lugares",
  emptyBody:
    "Agrega el primer lugar o importa registros de autoridad existentes.",
  goBack: "Volver",

  // Draft/changelog
  commit_note_placeholder: "Nota sobre los cambios (opcional)",
  autosave_saving: "Guardando...",
  autosave_saved: "Borrador guardado",
  conflict_banner:
    "{{name}} tiene cambios sin guardar desde {{time}}.",
  overwrite_confirm:
    "Este registro fue modificado por {{name}} a las {{time}}. ¿Desea sobreescribir?",
  overwrite_button: "Sobreescribir",
  overwrite_cancel: "Cancelar",

  // Linked descriptions
  linked_descriptions: "Descripciones vinculadas",
  no_linked_descriptions: "Sin descripciones vinculadas",
  add_description_link: "Vincular una descripción",
  search_descriptions: "Buscar descripciones...",
  select_role: "Seleccionar rol",
  link_button: "Vincular",
  edit_link: "Editar vínculo",
  remove_link: "Quitar vínculo",
  remove_link_confirm: "¿Quitar este vínculo?",
  duplicate_link_error: "Esta descripción ya está vinculada con este rol",
  role_note_label: "Nota del rol",

  // Place roles
  role_created: "Creado",
  role_subject: "Tema",
  role_mentioned: "Mencionado",
  role_sent_from: "Enviado desde",
  role_sent_to: "Recibido en",
  role_published: "Publicado",
  role_venue: "Lugar",
} as const;
