/**
 * Cloudflare Worker Environment Bindings
 *
 * This file declares the TypeScript shape of the `env` object that the
 * Worker receives on every request. It mirrors the bindings declared in
 * `wrangler.jsonc` — whenever a new D1 database, R2 bucket, KV namespace,
 * workflow, or secret is added to the wrangler config, it must also be
 * added here so loaders and actions can read it with type safety.
 *
 * The canonical type file — `worker-configuration.d.ts` — is generated by
 * `wrangler types` and is gitignored, so CI needs this hand-maintained
 * declaration for the typecheck step to pass without first running a
 * wrangler build.
 *
 * @version v0.6.0
 */
interface Env {
  DB: D1Database;
  BUCKET: R2Bucket;
  EXPORT_BUCKET: R2Bucket;
  MANIFESTS_BUCKET: R2Bucket;
  METS_BUCKET: R2Bucket;
  APP_NAME: string;
  SENDER_EMAIL: string;
  ALLOWED_MANIFEST_HOSTS: string;
  SESSION_SECRET: string;
  RESEND_API_KEY: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  // Import staging store (spec §7.4). BACKEND is the explicit selector —
  // "b2" in production, unset/anything else means R2 over BUCKET (dev,
  // tests). The four S3 vars back the B2 store and are only read when
  // BACKEND is "b2"; optional so dev/tests need not carry them.
  IMPORTS_STAGING_BACKEND?: string;
  IMPORTS_STAGING_S3_ENDPOINT: string;
  IMPORTS_STAGING_BUCKET: string;
  IMPORTS_STAGING_KEY_ID: string;
  IMPORTS_STAGING_SECRET_KEY: string;
}
