/**
 * English translations — entities namespace
 *
 * This locale namespace carries the English strings for the entities
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Entities follow ISAAR(CPF), so the labels
 * stay close to the standard's preferred phrasing.
 *
 * @version v0.4.3
 */
export default {
  // Page
  title: "Entities",
  primaryCta: "Add entity",

  // Form
  createTitle: "New entity",
  createSubmit: "Create entity",
  editSave: "Save changes",
  editButton: "Edit entity",
  discardButton: "Discard changes",
  backButton: "Back to entities",

  // Delete
  deleteButton: "Delete entity",
  deleteTitle: "Delete entity",
  deleteBody:
    "Are you sure you want to delete {{name}}? This action cannot be undone.",
  deleteBlocked: "Cannot delete — {{count}} linked descriptions",
  cascadeWarning: "This entity has {{count}} linked descriptions.",
  cascadeExamples: "Examples:",

  // Search
  searchPlaceholder: "Search entities...",
  advancedToggle: "Advanced search",
  advancedHide: "Hide advanced search",
  advancedActive: "Advanced search active",
  advancedClear: "Clear",
  advancedSearch: "Search",

  // Filter
  allTypes: "All types",
  person: "Person",
  family: "Family",
  corporate: "Corporate body",
  showMerged: "Show merged",
  filterByType: "Filter by type:",
  typeFilterAria: "Filter by type: {{type}}",
  attested: "Attested:",
  yearFromPlaceholder: "from",
  yearToPlaceholder: "to",
  yearFromAria: "Attested from year",
  yearToAria: "Attested to year",
  functionFilterPlaceholder: "Filter by function...",
  functionFilterAria: "Filter by function",
  reset: "Reset",
  resetAria: "Reset all filters",
  countLine: "Showing {{shown}} of {{total}} entities",
  undatedExcluded: "entities without dates are excluded by the year filter",
  sortByLinksAria: "Sort by number of linked descriptions",
  col_attested: "Attested",

  // Pagination
  previous: "Previous",
  next: "Next",
  showing: "Showing {{count}} entities",

  // Columns
  columnToggle: "Columns",

  // Merge
  mergeButton: "Merge",
  mergeTitle: "Merge entity",
  mergeSearch: "Search target record...",
  mergeReassignTitle: "Reassign links",
  mergeReassignSubtitle:
    "{{name}} has {{count}} linked descriptions",
  mergeConfirm: "Confirm merge",
  mergeCancel: "Cancel",
  mergedBanner: "This record was merged into {{target}}.",
  mergedBannerLink: "View target record",
  mergedSuffix: "(merged)",

  // Split
  splitButton: "Split",
  splitTitle: "Split entity",
  splitSubtitle:
    "A new record will be created with the data from {{name}}. Select the links that should be moved to the new record.",
  splitConfirm: "Confirm split",
  splitCancel: "Cancel",
  loadMore: "Load more",
  selectAll: "Select all",
  deselectAll: "Deselect all",

  // Success
  successCreated: "Entity created.",
  successUpdated: "Entity updated.",
  successDeleted: "Entity deleted.",
  successMerged: "Entity merged.",
  successSplit: "Entity split.",

  // Error
  errorGeneric: "An error occurred. Try again.",
  errorRequired: "This field is required.",
  errorInvalidLod: "Invalid format.",
  errorDuplicateCode: "An entity with that code already exists.",

  // Field labels
  "field.displayName": "Display name",
  "field.sortName": "Sort name",
  "field.surname": "Surname",
  "field.givenName": "Given name",
  "field.honorific": "Honorific",
  "field.entityType": "Entity type",
  "field.entityCode": "Entity code",
  "field.nameVariants": "Name variants",
  "field.datesOfExistence": "Dates of existence",
  "field.dateStart": "Start date",
  "field.dateEnd": "End date",
  "field.history": "History",
  "field.primaryFunction": "Primary function",
  primary_function_placeholder: "Search or type a function...",
  "field.legalStatus": "Legal status",
  "field.functions": "Functions",
  "field.mergedInto": "Merged into",
  "field.sources": "Sources",
  "field.wikidataId": "Wikidata",
  "field.viafId": "VIAF",
  "field.dbeId": "DBE",
  "field.links": "Links",
  "field.notes": "Notes",
  "field.internalNotes": "Internal notes",
  "field.createdAt": "Created",
  "field.updatedAt": "Updated",

  // Section headings
  sectionIdentity: "Identity area",
  sectionDescription: "Description area",
  sectionRelationships: "Relationships",
  sectionControl: "Control",
  sectionNotes: "Notes",
  sectionInternalNotes: "Internal notes",
  internalBadge: "Internal",

  // Misc
  autoGenerated: "Auto-generated.",
  addVariant: "Add variant",
  breadcrumbNew: "New entity",
  emptyHeading: "No entities",
  emptyBody:
    "Add the first entity or import existing authority records.",
  goBack: "Go back",

  // Draft/changelog
  commit_note_placeholder: "Note about changes (optional)",
  autosave_saving: "Saving...",
  autosave_saved: "Draft saved",
  conflict_banner:
    "{{name}} has unsaved changes since {{time}}.",
  overwrite_confirm:
    "This record was modified by {{name}} at {{time}}. Do you want to overwrite?",
  overwrite_button: "Overwrite",
  overwrite_cancel: "Cancel",

  // Linked descriptions
  linked_descriptions: "Linked descriptions",
  no_linked_descriptions: "No linked descriptions",
  add_description_link: "Link a description",
  search_descriptions: "Search descriptions...",
  select_role: "Select role",
  link_button: "Link",
  edit_link: "Edit link",
  remove_link: "Remove link",
  remove_link_confirm: "Remove this link?",
  duplicate_link_error: "This description is already linked with this role",
  role_note_label: "Role note",
  sequence_label: "Sequence",
  honorific_label: "Honorific",
  function_label: "Function",
  name_as_recorded_label: "Name as recorded",

  // Entity roles (must match ENTITY_ROLES in lib/validation/enums.ts)
  role_creator: "Creator",
  role_author: "Author",
  role_editor: "Editor",
  role_publisher: "Publisher",
  role_sender: "Sender",
  role_recipient: "Recipient",
  role_mentioned: "Mentioned",
  role_subject: "Subject",
  role_scribe: "Scribe",
  role_witness: "Witness",
  role_notary: "Notary",
  role_photographer: "Photographer",
  role_artist: "Artist",
  role_plaintiff: "Plaintiff",
  role_defendant: "Defendant",
  role_petitioner: "Petitioner",
  role_judge: "Judge",
  role_appellant: "Appellant",
  role_official: "Official",
  role_heir: "Heir",
  role_albacea: "Executor",
  role_spouse: "Spouse",
  role_victim: "Victim",
  role_grantor: "Grantor",
  role_donor: "Donor",
  role_seller: "Seller",
  role_buyer: "Buyer",
  role_mortgagor: "Mortgagor",
  role_mortgagee: "Mortgagee",
  role_creditor: "Creditor",
  role_debtor: "Debtor",
  role_fiador: "Surety",
  role_apoderado: "Attorney-in-Fact",

  // Detail-page redesign: LOD card
  sectionLod: "Linked open data",
} as const;
