/**
 * English translations — places namespace
 *
 * This locale namespace carries the English strings for the places
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Places follow the Linked Places conventions
 * the rest of the entities surface uses.
 *
 * @version v0.4.3
 */
export default {
  // Page
  title: "Places",
  primaryCta: "Add place",

  // Form
  createTitle: "New place",
  createSubmit: "Create place",
  editSave: "Save changes",
  editButton: "Edit place",
  discardButton: "Discard changes",
  backButton: "Back to places",

  // Delete
  deleteButton: "Delete place",
  deleteTitle: "Delete place",
  deleteBody:
    "Are you sure you want to delete {{name}}? This action cannot be undone.",
  deleteBlocked: "Cannot delete — {{count}} linked descriptions",
  cascadeWarning: "This place has {{count}} linked descriptions.",
  cascadeExamples: "Examples:",

  // Search
  searchPlaceholder: "Search places...",
  advancedToggle: "Advanced search",
  advancedHide: "Hide advanced search",
  advancedActive: "Advanced search active",
  advancedClear: "Clear",
  advancedSearch: "Search",

  // Filter
  allTypes: "All types",
  country: "Country",
  region: "Region",
  department: "Department",
  province: "Province",
  partido: "Partido",
  city: "City",
  town: "Town",
  parish: "Parish",
  hacienda: "Hacienda",
  mine: "Mine",
  river: "River",
  other: "Other",
  showMerged: "Show merged",

  // Pagination
  previous: "Previous",
  next: "Next",
  showing: "Showing {{count}} places",

  // Columns
  columnToggle: "Columns",

  // Merge
  mergeButton: "Merge",
  mergeTitle: "Merge place",
  mergeSearch: "Search target record...",
  mergeReassignTitle: "Reassign links",
  mergeReassignSubtitle:
    "{{name}} has {{count}} linked descriptions",
  mergeConfirm: "Confirm merge",
  mergeCancel: "Cancel",
  mergedBanner: "This record was merged into {{target}}.",
  mergedBannerLink: "View target record",
  mergedSuffix: "(merged)",

  // Split
  splitButton: "Split",
  splitTitle: "Split place",
  splitSubtitle:
    "A new record will be created with the data from {{name}}. Select the links that should be moved to the new record.",
  splitConfirm: "Confirm split",
  splitCancel: "Cancel",
  loadMore: "Load more",
  selectAll: "Select all",
  deselectAll: "Deselect all",

  // Success
  successCreated: "Place created.",
  successUpdated: "Place updated.",
  successDeleted: "Place deleted.",
  successMerged: "Place merged.",
  successSplit: "Place split.",

  // Error
  errorGeneric: "An error occurred. Try again.",
  errorRequired: "This field is required.",
  errorInvalidLod: "Invalid format.",
  errorDuplicateCode: "A place with that code already exists.",

  // Field labels
  "field.label": "Name",
  "field.displayName": "Display name",
  "field.placeCode": "Place code",
  "field.placeType": "Place type",
  "field.nameVariants": "Name variants",
  "field.parentId": "Parent place",
  "field.historicalGobernacion": "Gobernacion",
  "field.historicalPartido": "Partido",
  "field.historicalRegion": "Region",
  "field.countryCode": "Country code",
  "field.adminLevel1": "Admin level 1",
  "field.adminLevel2": "Admin level 2",
  "field.latitude": "Latitude",
  "field.longitude": "Longitude",
  "field.coordinatePrecision": "Coordinate precision",
  "field.mergedInto": "Merged into",
  "field.tgnId": "TGN",
  "field.hgisId": "HGIS",
  "field.whgId": "WHG",
  "field.wikidataId": "Wikidata",
  "field.notes": "Notes",
  "field.internalNotes": "Internal notes",
  "field.createdAt": "Created",
  "field.updatedAt": "Updated",

  // Section headings
  sectionIdentity: "Identity",
  sectionHistorical: "Historical context",
  sectionGeography: "Modern geography and LOD",
  sectionControl: "Control",
  sectionNotes: "Notes",
  sectionInternalNotes: "Internal notes",
  internalBadge: "Internal",

  // Coordinate precision
  precisionExact: "Exact",
  precisionApproximate: "Approximate",
  precisionCentroid: "Centroid",
  precisionUncertain: "Uncertain",

  // Misc
  autoGenerated: "Auto-generated.",
  addVariant: "Add variant",
  breadcrumbNew: "New place",
  emptyHeading: "No places",
  emptyBody:
    "Add the first place or import existing authority records.",
  goBack: "Go back",

  // Draft/changelog
  commit_note_placeholder: "Note about changes (optional)",
  autosave_saving: "Saving...",
  autosave_saved: "Draft saved",
  conflict_banner:
    "{{name}} has unsaved changes since {{time}}.",
  overwrite_confirm:
    "This record was modified by {{name}} at {{time}}. Do you want to overwrite?",
  overwrite_button: "Overwrite",
  overwrite_cancel: "Cancel",

  // Linked descriptions
  linked_descriptions: "Linked descriptions",
  no_linked_descriptions: "No linked descriptions",
  add_description_link: "Link a description",
  search_descriptions: "Search descriptions...",
  select_role: "Select role",
  link_button: "Link",
  edit_link: "Edit link",
  remove_link: "Remove link",
  remove_link_confirm: "Remove this link?",
  duplicate_link_error: "This description is already linked with this role",
  role_note_label: "Role note",

  // Place roles
  role_created: "Created",
  role_subject: "Subject",
  role_mentioned: "Mentioned",
  role_sent_from: "Sent from",
  role_sent_to: "Sent to",
  role_published: "Published",
  role_venue: "Venue",
  // Coordinates column + geocoding worklist (design surface 7)
  "field.coordinates": "Coordinates",
  missingCoordsChip: "Missing coordinates",
  reviewCoordsChip: "Coordinates to review",
  reviewBadge: "to review",
  missingCoordsNotice:
    "{{count}} places have no coordinates yet — this filter is the geocoding worklist.",
  viewTable: "Table view",
  viewMap: "Map view",

  // Map explorer (design surface 8)
  mapNoCoordsNotice: "{{count}} places have no coordinates yet",
  mapReview: "Review",
  mapFilterToggle: "Filter list to map view",
  mapInView: "{{count}} places in view",
  mapTotal: "{{count}} total",
  mapEmptyTitle: "No places in this view",
  mapEmptyBody: "Zoom out or pan to find located places.",
  mapOpenRecord: "Open record",
  mapDescriptions: "{{count}} descriptions",
  mapZoomIn: "Zoom in",
  mapZoomOut: "Zoom out",

  // Map preview (design surface 9)
  previewPrecision: "Precision · {{value}}",
  previewNoCoords: "No coordinates yet",
  previewSetCoords: "Set coordinates",

  // Coordinate editor (design surface 10)
  coordClickPrompt: "Click the map to set a location",
  coordDragHint: "Drag the pin to adjust",
  coordPrecisionLabel: "Precision",
  // Empty (unset) option label for the precision select.
  coordPrecisionUnset: "Not recorded",

  // Combined places surface (spec §5 — one list+map page)
  linkCount_one: "{{count}} link",
  linkCount_other: "{{count}} links",
  noPin: "no pin",
  loadingMore: "Loading…",
  listEmptyTitle: "No places in this list",
  listEmptyBody: "Adjust the search or filters to see places here.",
  mapDimmed: "The map is empty while the missing-coordinates filter is on.",
  paneList: "List",
  paneMap: "Map",
  countBrowse:
    "Showing {{shown}} of {{total}} places · {{located}} with coordinates · {{without}} without coordinates",
  countMissing:
    "Showing {{shown}} of {{total}} places without coordinates — the geocoding worklist",
  countReview:
    "Showing {{shown}} of {{total}} places to review — coordinates flagged uncertain",
  countViewport:
    "Showing {{shown}} of {{inView}} matches in view · {{located}} places have coordinates · {{without}} without coordinates are excluded while the viewport filter is on",
  countMergedSuffix_one: "· {{count}} merged record shown",
  countMergedSuffix_other: "· {{count}} merged records shown",
  extHas: "Has {{id}}",
  extMissing: "Missing {{id}}",
  extFilterAria: "Filter by {{id}}",
  extClearAria: "Clear the {{id}} filter",
  resetFilters: "Reset",

  // Detail-page redesign: LOD card + geocoding search (edit mode)
  sectionLod: "Linked open data",
  geocodePlaceholder: "Search a modern place name…",
  geocodeNoResults: "No results",
  geocodeUnavailable:
    "Place search is unavailable right now — set the location on the map or type the coordinates.",
} as const;
