/**
 * English translations — places namespace
 *
 * This locale namespace carries the English strings for the places
 * admin surface — the page heading, the create/edit form, and the
 * primary call-to-action. Places follow the Linked Places conventions
 * the rest of the entities surface uses.
 *
 * @version v0.3.0
 */
export default {
  // Page
  title: "Places",
  primaryCta: "Add place",

  // Form
  createTitle: "New place",
  createSubmit: "Create place",
  editSave: "Save changes",
  editButton: "Edit place",
  discardButton: "Discard changes",
  backButton: "Back to places",

  // Delete
  deleteButton: "Delete place",
  deleteTitle: "Delete place",
  deleteBody:
    "Are you sure you want to delete {{name}}? This action cannot be undone.",
  deleteBlocked: "Cannot delete — {{count}} linked descriptions",
  cascadeWarning: "This place has {{count}} linked descriptions.",
  cascadeExamples: "Examples:",

  // Search
  searchPlaceholder: "Search places...",
  advancedToggle: "Advanced search",
  advancedHide: "Hide advanced search",
  advancedActive: "Advanced search active",
  advancedClear: "Clear",
  advancedSearch: "Search",

  // Filter
  allTypes: "All types",
  country: "Country",
  region: "Region",
  department: "Department",
  province: "Province",
  partido: "Partido",
  city: "City",
  town: "Town",
  parish: "Parish",
  hacienda: "Hacienda",
  mine: "Mine",
  river: "River",
  other: "Other",
  showMerged: "Show merged",

  // Pagination
  previous: "Previous",
  next: "Next",
  showing: "Showing {{count}} places",

  // Columns
  columnToggle: "Columns",

  // Merge
  mergeButton: "Merge",
  mergeTitle: "Merge place",
  mergeSearch: "Search target record...",
  mergeReassignTitle: "Reassign links",
  mergeReassignSubtitle:
    "{{name}} has {{count}} linked descriptions",
  mergeConfirm: "Confirm merge",
  mergeCancel: "Cancel",
  mergedBanner: "This record was merged into {{target}}.",
  mergedBannerLink: "View target record",
  mergedSuffix: "(merged)",

  // Split
  splitButton: "Split",
  splitTitle: "Split place",
  splitSubtitle:
    "A new record will be created with the data from {{name}}. Select the links that should be moved to the new record.",
  splitConfirm: "Confirm split",
  splitCancel: "Cancel",
  loadMore: "Load more",
  selectAll: "Select all",
  deselectAll: "Deselect all",

  // Success
  successCreated: "Place created.",
  successUpdated: "Place updated.",
  successDeleted: "Place deleted.",
  successMerged: "Place merged.",
  successSplit: "Place split.",

  // Error
  errorGeneric: "An error occurred. Try again.",
  errorRequired: "This field is required.",
  errorInvalidLod: "Invalid format.",
  errorDuplicateCode: "A place with that code already exists.",

  // Field labels
  "field.label": "Name",
  "field.displayName": "Display name",
  "field.placeCode": "Place code",
  "field.placeType": "Place type",
  "field.nameVariants": "Name variants",
  "field.parentId": "Parent place",
  "field.historicalGobernacion": "Gobernacion",
  "field.historicalPartido": "Partido",
  "field.historicalRegion": "Region",
  "field.countryCode": "Country code",
  "field.adminLevel1": "Admin level 1",
  "field.adminLevel2": "Admin level 2",
  "field.latitude": "Latitude",
  "field.longitude": "Longitude",
  "field.coordinatePrecision": "Coordinate precision",
  "field.mergedInto": "Merged into",
  "field.tgnId": "TGN",
  "field.hgisId": "HGIS",
  "field.whgId": "WHG",
  "field.wikidataId": "Wikidata",
  "field.createdAt": "Created",
  "field.updatedAt": "Updated",

  // Section headings
  sectionIdentity: "Identity",
  sectionHistorical: "Historical context",
  sectionGeography: "Modern geography and LOD",
  sectionControl: "Control",

  // Coordinate precision
  precisionExact: "Exact",
  precisionApproximate: "Approximate",
  precisionCentroid: "Centroid",

  // Misc
  autoGenerated: "Auto-generated.",
  addVariant: "Add variant",
  breadcrumbNew: "New place",
  emptyHeading: "No places",
  emptyBody:
    "Add the first place or import existing authority records.",
  goBack: "Go back",

  // Draft/changelog
  commit_note_placeholder: "Note about changes (optional)",
  autosave_saving: "Saving...",
  autosave_saved: "Draft saved",
  conflict_banner:
    "{{name}} has unsaved changes since {{time}}.",
  overwrite_confirm:
    "This record was modified by {{name}} at {{time}}. Do you want to overwrite?",
  overwrite_button: "Overwrite",
  overwrite_cancel: "Cancel",

  // Linked descriptions
  linked_descriptions: "Linked descriptions",
  no_linked_descriptions: "No linked descriptions",
  add_description_link: "Link a description",
  search_descriptions: "Search descriptions...",
  select_role: "Select role",
  link_button: "Link",
  edit_link: "Edit link",
  remove_link: "Remove link",
  remove_link_confirm: "Remove this link?",
  duplicate_link_error: "This description is already linked with this role",
  role_note_label: "Role note",

  // Place roles
  role_created: "Created",
  role_subject: "Subject",
  role_mentioned: "Mentioned",
  role_sent_from: "Sent from",
  role_sent_to: "Sent to",
  role_published: "Published",
  role_venue: "Venue",
} as const;
